# Cloudflare Pages Configuration
name = "trackshare"
pages_build_output_dir = "dist"
functions_directory = "functions"
compatibility_date = "2023-10-12"
compatibility_flags = ["nodejs_compat"]

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"